// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  progressBar: string;
  progressBarContainer: string;
}
declare const cssExports: CssExports;
export default cssExports;
